name: job outputs

on:
  push:
    branches: ['main']

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      job1_name: ${{steps.set-output.outputs.name}}

    steps:
      - name: set output
        id: set-output
        shell: bash
        run: |
          echo "name=siva" >> $GITHUB_OUTPUT
          echo "age=27" >> $GITHUB_OUTPUT

      - name: access output
        run: echo "value is ${{steps.set-output.outputs.name}}"

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: access output2
        run: echo "value is ${{needs.job1.outputs.job1_name}}"
        
  
