name: Hellow world

on:
  # push: 
  #   branches: ["main"]
  workflow_dispatch:
    inputs:
      name:
        description: "Testing"
        type: string
        default: 'Test'

jobs:
  manual-workflow:
    runs-on: ubuntu-latest

    steps:
    - name: Greeting
      run: echo ${{inputs.name}}
