name: Manual work flow

on:
  # push: 
  #   branches: ["main"]
  workflow_dispatch:
    inputs:
      name:
        description: "Testing"
        type: string
        default: 'Test'
      age:
        description: 'Enter age'
        type: number
        required: true
      married:
        description: 'Is she married ?'
        type: boolean
        

jobs:
  manual-workflow:
    runs-on: ubuntu-latest

    steps:
    - name: Greeting
      run: echo ${{inputs.name}}
    - name: Greeting
      run: echo ${{inputs.age}}
    - name: Greeting
      run: echo ${{inputs.married}}
