name: schedule workflow

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  cron:
    runs-on: ubuntu-latest

    steps:
      - name: Schedule workflow
        run: |
          current_date_time=$(date)
          echo "current date is $current_date_time"
