name: set output

on:

  push:
    branches: ['main']

jobs:
  set-output:
    runs-on: ubuntu-latest

    steps:
      - name: setoutput
        id: set-output
        shell: bash
        run: |
          echo "Name=siva" >> $GITHUB_OUTPUT
          echo "Age=27" >> $GITHUB_OUTPUT

      - name: Access output
        run: |
          echo "value of output is ${{steps.set-output.outputs.Name}}"
          echo "value of output is ${{steps.set-output.outputs.Age}}"
